export const statsTitles = {
  twoPointsMade: '2-MADE',
  twoPointsMiss: '2-MISS',
  threePointsMade: '3-MADE',
  threePointsMiss: '3-MISS',
  freeThrowMade: 'FT-MADE',
  freeThrowMiss: 'FT-MISS',
  offensiveRebounds: 'OFF-REB',
  defensiveRebounds: 'DEF-REB',
  assists: 'ASS',
  steals: 'STL',
  blocks: 'BLK',
  turnovers: 'TO',
  fouls: 'FOUL',
};
