export const statsTitles = {
  twoPointsMade: '兩分投進',
  twoPointsMiss: '兩分不進',
  threePointsMade: '三分投進',
  threePointsMiss: '三分不進',
  freeThrowMade: '罰球投進',
  freeThrowMiss: '罰球不進',
  offensiveRebounds: '進攻籃板',
  defensiveRebounds: '防守籃板',
  assists: '助攻',
  steals: '抄截',
  blocks: '火鍋',
  turnovers: '失誤',
  fouls: '犯規',
};
